### ISSUE TITLE
OSCLOUD version needs to be rebuilt against console_bridge_1.0

### ISSUE THREAD

**Issue by okasha55** [ros-melodic-arch/ros-melodic-image-transport#1]
the binary version causes errors and warnings like this
/usr/bin/ld: warning: libconsole_bridge.so.0.4, needed by /opt/ros/melodic/lib/libnodeletlib.so, not found (try using -rpath or -rpath-link)
because console-bridge is updated to version 1.0

**Comment by bionade24** [comment]
On it.

**Comment by bionade24** [comment]
Solved.
